/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build shadcn INSTALL.md for generated registry.json.
 *
 * @see https://ui.shadcn.com/docs/registry
 */
export function renderInstallMd(options: {
  configFile: string;
  name?: string;
}): string {
  const registryName = options.name ?? "acme";

  return `# Installing shadcn Registry

Generated by \`@razorwind/shadcn\`.

## Files

- \`${options.configFile}\` — shadcn registry manifest (registry.json schema)

## Setup

1. Ensure \`components.json\` points at this registry URL or local path.

2. Add items from the registry:

\`\`\`bash
npx shadcn@latest add button --registry ./${options.configFile}
\`\`\`

Or publish \`${options.configFile}\` and reference it in \`components.json\`:

\`\`\`json
{
  "registries": {
    "@${registryName}": "./${options.configFile}"
  }
}
\`\`\`

3. Re-run Razorwind generate when Razorwind components change so the registry stays current.

## Regenerate

\`${options.configFile}\` is generated — update Razorwind schema components instead of editing by hand.
`;
}
