/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import { definePlugin } from "@razorwind/core/plugin";
import type { Schema } from "@razorwind/core/schema";
import { createDocument } from "@razorwind/core/utils";
import { stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { buildManifest } from "./manifest";
import { createDesignSystemPlugin } from "./runtime";
import type {
  DesignSystemManifest,
  DesignSystemRuleId,
  EslintPluginOptions
} from "./types";

export {
  buildManifest,
  collectManifestComponents,
  collectManifestIcons,
  collectManifestTokens,
  DEFAULT_PREFIX,
  kebabCase,
  pascalCase,
  resolveCategory
} from "./manifest";
export type {
  ComponentRole,
  CoreRuleId,
  DesignSystemManifest,
  DesignSystemOptions,
  DesignSystemRuleId,
  DesignSystemSettings,
  DesignSystemSeverity,
  EslintPluginOptions,
  ManifestComponent,
  ManifestFont,
  ManifestToken,
  TokenCategory,
  TokenReferenceStyle
} from "./types";

const DEFAULT_ESLINT_PATH = "eslint/design-system/index.mjs";
const DEFAULT_RUNTIME_IMPORT = "@razorwind/eslint/runtime";

/**
 * Render the ESLint plugin module that binds the design-system runtime to
 * the schema-derived manifest.
 */
export function renderEslintPlugin(
  manifest: DesignSystemManifest,
  options: Pick<EslintPluginOptions, "runtimeImport" | "eslintPath"> = {}
): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;
  // Annotating the manifest in TypeScript output keeps declaration emit from
  // inferring (and printing) a structural type for the whole literal.
  const typed = /\.[cm]?tsx?$/.test(options.eslintPath ?? DEFAULT_ESLINT_PATH);

  return `// Generated by @razorwind/eslint. Do not edit by hand: re-run
// Razorwind generate when design tokens change.
//
//   import designSystem from "./<path-to-this-file>";
//   export default [
//     ...,
//     designSystem({ files: ["src/**/*.{ts,tsx}"] })
//   ];

import { createDesignSystemPlugin${typed ? ", type DesignSystemManifest" : ""} } from ${JSON.stringify(runtimeImport)};

export const manifest${typed ? ": DesignSystemManifest" : ""} = ${JSON.stringify(manifest, null, 2)};

const designSystem = createDesignSystemPlugin(manifest);

export const plugin = designSystem.plugin;
export const rules = designSystem.rules;
export const configs = designSystem.configs;
export const defaultSeverity = designSystem.defaultSeverity;

export default designSystem.config;
`;
}

/**
 * Build the ESLint INSTALL.md for the generated plugin module, listing every
 * rule with the default severity the schema gives it.
 */
export function renderEslintInstallMd(options: {
  eslintPath: string;
  manifest: DesignSystemManifest;
}): string {
  const { eslintPath, manifest } = options;
  const { rules, defaultSeverity } = createDesignSystemPlugin(manifest);
  const rows = (Object.keys(rules) as DesignSystemRuleId[])
    .map(id => {
      const rule = rules[id]!;

      return `| \`${manifest.prefix}/${id}\` | ${defaultSeverity[id] ?? "off"} | ${rule.meta.docs.description} |`;
    })
    .join("\n");
  const counts = [
    `${manifest.tokens.length} tokens`,
    `${manifest.components.length} components`,
    `${manifest.icons.length} icons`,
    `${manifest.fonts.length} fonts`
  ].join(", ");

  return `# Installing the ESLint Design-System Plugin

Generated by \`@razorwind/eslint\` from ${counts}.

## Files

- \`${eslintPath}\` — ESLint flat-config plugin whose rules are derived from the design system

## Setup

1. Install the runtime the generated module imports:

\`\`\`bash
pnpm add -D @razorwind/eslint
\`\`\`

2. Add the plugin to \`eslint.config.mjs\`:

\`\`\`js
import designSystem from "./${eslintPath}";

export default [
  // ...
  designSystem({
    files: ["src/**/*.{ts,tsx}"],
    // How suggested fixes reference tokens: "css-var" or "function".
    tokenReference: "css-var",
    // Only treat components imported from these modules as design-system components.
    // componentModules: ["@acme/ui"],
    severity: { "no-physical-properties": "error" }
  })
];
\`\`\`

3. Deliberate one-offs carry an inline, reviewable exception:

\`\`\`ts
// eslint-disable-next-line ${manifest.prefix}/ensure-design-token-usage -- <reason>
\`\`\`

## Rules

Token rules are enabled when the design system defines that token category,
and component rules when it defines the replacement component.

| Rule | Default | Description |
| ---- | ------- | ----------- |
${rows}

## Regenerate

Re-run Razorwind generate when the design system changes so \`${eslintPath}\` stays in sync.
`;
}

/**
 * Generate an ESLint plugin whose rules are derived from the schema's design
 * tokens, components, icons and fonts.
 */
export async function generateEslintPlugin(
  spec: Schema,
  options: EslintPluginOptions = {},
  cwd: string = process.cwd()
): Promise<GeneratorFunctionResult<Schema, EslintPluginOptions>> {
  const manifest = buildManifest(spec, options);
  if (
    manifest.tokens.length === 0 &&
    manifest.components.length === 0 &&
    manifest.icons.length === 0
  ) {
    return {};
  }

  const eslintPath = options.eslintPath ?? DEFAULT_ESLINT_PATH;
  const existingPath = await stat(resolve(cwd, eslintPath)).catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return undefined;
      throw error;
    }
  );
  if (existingPath?.isDirectory()) {
    throw new Error(
      `eslintPath must be a filename, not an existing directory: "${eslintPath}". Set eslintPath to "${join(eslintPath, "index.mjs")}" instead.`
    );
  }

  const installPath = join(dirname(eslintPath), "INSTALL.md");
  const meta = { name: "razorwind-eslint" };

  return {
    [eslintPath]: createDocument<Schema, EslintPluginOptions>(
      eslintPath,
      renderEslintPlugin(manifest, options),
      meta,
      undefined,
      "javascript"
    ),
    [installPath]: createDocument<Schema, EslintPluginOptions>(
      installPath,
      options.installGuide ?? renderEslintInstallMd({ eslintPath, manifest }),
      meta,
      undefined,
      "markdown"
    )
  };
}

/**
 * Razorwind plugin: generate an ESLint plugin that keeps code aligned with
 * the design system. It ports the `@atlaskit/eslint-plugin-design-system`
 * rules onto the schema's own tokens and components, and bundles the
 * `@razorwind/tailwindcss` (and optionally `@razorwind/tamagui`) guardrails.
 *
 * @example
 * ```ts
 * import { defineConfig } from "@razorwind/core";
 * import eslint from "@razorwind/eslint";
 *
 * export default defineConfig({
 *   plugins: [eslint({ prefix: "acme" })]
 * });
 * ```
 */
export default definePlugin((options?: EslintPluginOptions) => ({
  name: "eslint",
  themeGeneration: "combined",
  generate: async (spec, config) =>
    generateEslintPlugin(spec, options ?? {}, config.cwd)
}));
