/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";
import type { ChromeTheme } from "./types";

/**
 * Build Chrome INSTALL.md for generated extension theme folders.
 *
 * Steps follow loading an unpacked extension, as used by community themes such
 * as [Dracula for Chrome](https://github.com/dracula/google-chrome).
 */
export function renderInstallMd(options: {
  themes: Array<{
    name: string;
    displayName: string;
    folderName: string;
    imagePaths?: string[];
    iconPaths?: string[];
  }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1 ? primary.displayName : "Chrome Themes");

  const fileList = options.themes
    .map(theme => {
      const files = [`\`${theme.folderName}/manifest.json\``];
      const assets = [
        ...(theme.imagePaths ?? []),
        ...(theme.iconPaths ?? [])
      ];
      if (assets.length > 0) {
        files.push(
          assets.map(path => `\`${theme.folderName}/${path}\``).join(", ")
        );
      }
      return `- ${files.join(" + ")} — ${theme.displayName}`;
    })
    .join("\n");

  const themeChoices = options.themes
    .map(theme => `- **${theme.displayName}** — folder \`${theme.folderName}/\``)
    .join("\n");

  const hasAssets = options.themes.some(
    theme => (theme.imagePaths?.length ?? 0) > 0 || (theme.iconPaths?.length ?? 0) > 0
  );
  const assetNote = hasAssets
    ? `
If a theme references images or icons, copy the PNG files into the theme folder
using the paths from \`manifest.json\` before loading the extension.
`
    : "";

  return `# Installing ${displayName}

Generated by \`@razorwind/chrome\`.

These themes target [Google Chrome](https://www.google.com/chrome/) and other
Chromium browsers. Install steps follow the same pattern as
[Dracula for Chrome](https://github.com/dracula/google-chrome).

## Files

${fileList}
${assetNote}
## Setup

1. Open Chrome and go to \`chrome://extensions\`.

2. Enable **Developer mode** (toggle in the toolbar).

3. Click **Load unpacked** and select a generated theme folder (for example
   \`${primary.folderName}/\`). The folder must contain \`manifest.json\`.

4. Repeat for each theme variant you want installed.

To publish publicly, zip each theme folder and upload it to the
[Chrome Web Store](https://chrome.google.com/webstore/devconsole).

## Select / load theme

Chrome applies the theme immediately after loading the extension. To switch
between installed themes, disable one theme extension and enable another under
\`chrome://extensions\`, or remove themes you no longer need:

${themeChoices}
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: ChromeTheme): string {
  return resolveThemeDisplayName(theme);
}
