/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";
import type { ShikiTheme } from "./types";

/**
 * Build Shiki INSTALL.md for generated theme JSON files.
 *
 * @see https://shiki.style/guide/load-theme
 */
export function renderInstallMd(options: {
  themes: Array<{ name: string; displayName: string; fileName: string }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1 ? primary.displayName : "Shiki Themes");

  const fileList = options.themes
    .map(
      theme =>
        `- \`${theme.fileName}\` — ${theme.displayName} (theme id: \`${theme.name}\`)`
    )
    .join("\n");

  const themeIds = options.themes
    .map(theme => `- \`${theme.name}\` — ${theme.displayName}`)
    .join("\n");

  return `# Installing ${displayName}

Generated by \`@razorwind/shiki\`.

## Files

${fileList}

## Setup

1. Copy or import the generated JSON into your app (paths depend on your bundler).

2. Register themes when creating a Shiki highlighter:

\`\`\`ts
import { createHighlighter } from "shiki";
import theme from "./${primary.fileName}";

const highlighter = await createHighlighter({
  themes: [theme],
  langs: ["javascript"]
});

const html = highlighter.codeToHtml("const x = 1", {
  lang: "javascript",
  theme: "${primary.name}"
});
\`\`\`

Or load at runtime:

\`\`\`ts
import { readFile } from "node:fs/promises";

const theme = JSON.parse(
  await readFile("./${primary.fileName}", "utf8")
);
await highlighter.loadTheme(theme);
\`\`\`

## Select / load theme

Pass the theme id to \`codeToHtml\`, \`codeToTokens\`, or \`getTokenStyle\`:

${themeIds}
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: ShikiTheme): string {
  return resolveThemeDisplayName(theme);
}
