/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build Storybook INSTALL.md for generated token docs.
 *
 * @see https://storybook.js.org/docs/writing-docs/mdx
 */
export function renderInstallMd(options: {
  outputPath: string;
  titlePrefix?: string;
  themeFiles?: string[];
  themeNames?: string[];
}): string {
  const titlePrefix = options.titlePrefix ?? "Design Tokens";
  const themeFile = options.themeFiles?.[0];
  const themeNames = options.themeNames ?? [];
  const themeSection = themeFile
    ? themeNames.length > 1
      ? `
## Storybook UI theme

Generated theme module:

- \`${themeFile}\` — record of \`create()\` themes keyed by name (${themeNames
          .map(name => `\`${name}\``)
          .join(", ")})

Wire into \`.storybook/preview.ts\`:

\`\`\`ts
import themes from "../${themeFile}";

export const parameters = {
  docs: { theme: themes[${JSON.stringify(themeNames[0])}] }
};
\`\`\`
`
      : `
## Storybook UI theme

Generated theme module(s):

- \`${themeFile}\`

Wire into \`.storybook/preview.ts\`:

\`\`\`ts
import theme from "../${themeFile}";

export const parameters = {
  docs: { theme }
};
\`\`\`
`
    : "";

  return `# Installing Storybook Token Docs

Generated by \`@razorwind/storybook\`.

## Files

- \`${options.outputPath}/Tokens.mdx\` — token overview (${titlePrefix})
- \`${options.outputPath}/blocks/\` — React doc blocks (ColorPalette, Typeset, …)
- \`${options.outputPath}/tokens.json\` — flattened token manifest
${themeSection}
## Setup

1. Add the generated MDX pages to Storybook (paths depend on your \`stories\` config):

\`\`\`ts
// .storybook/main.ts
export default {
  stories: [
    "../${options.outputPath}/**/*.mdx"
  ]
};
\`\`\`

2. Import doc blocks in MDX as needed:

\`\`\`mdx
import { ColorPaletteBlock } from "./blocks";
\`\`\`

3. Start Storybook and open **${titlePrefix}** in the sidebar.

## Regenerate

Re-run Razorwind generate when tokens change to refresh docs under \`${options.outputPath}/\`.
`;
}
