packages:
  - tools/*
  - packages/*
  - docs/*
  - playground/*
catalog:
  "@ls-lint/ls-lint": ^2.3.1
  "@nx/devkit": 23.1.0
  "@nx/eslint-plugin": 23.1.0
  "@nx/js": 23.1.0
  "@nx/plugin": 23.1.0
  "@nx/vite": 23.1.0
  "@nx/vitest": 23.1.0
  "@nx/workspace": 23.1.0
  "@power-plant/core": ^0.0.92
  "@power-plant/dtcg-schema": ^0.0.1
  "@power-plant/schema": ^0.0.90
  "@power-plant/utils": ^0.0.78
  "@powerlines/plugin-env": ^0.16.421
  "@powerlines/nx": ^0.13.252
  "@powerlines/plugin-untyped": ^0.2.628
  "@powerlines/tsconfig": ^0.4.256
  "@powerlines/tsdoc": ^0.2.204
  "@powerlines/plugin-tsdown": ^0.1.613
  "@shell-shock/eslint-plugin": ^0.0.89
  "@shell-shock/preset-cli": ^0.9.37
  "@shell-shock/core": ^0.17.25
  "@shell-shock/nx": ^0.0.98
  "@storm-software/config": ^1.138.75
  "@storm-software/config-tools": ^1.190.138
  "@storm-software/cspell": ^0.46.205
  "@storm-software/eslint-plugin-pnpm": ^0.0.101
  "@storm-software/eslint-config-react": ^0.0.95
  "@storm-software/eslint-plugin-tsdoc": ^0.0.101
  "@storm-software/git-tools": ^2.131.147
  "@storm-software/linting-tools": ^1.134.68
  "@storm-software/markdownlint": ^0.30.293
  "@storm-software/pnpm-tools": ^0.7.153
  "@storm-software/prettier": ^0.59.191
  "@storm-software/tsconfig": ^0.48.204
  "@storm-software/untyped": ^0.24.280
  "@storm-software/workspace-tools": ^1.297.8
  "@stryke/env": ^0.20.133
  "@stryke/fs": ^0.33.116
  "@stryke/hash": ^0.13.69
  "@stryke/helpers": ^0.10.54
  "@stryke/path": ^0.29.41
  "@stryke/string-format": ^0.17.56
  "@stryke/type-checks": ^0.6.47
  "@stryke/types": ^0.12.42
  "@stryke/url": ^0.4.66
  "@tailwindcss/node": ^4.3.3
  "@types/node": ^25.9.7
  "@typescript/native-preview": 7.0.0-dev.20251218.3
  c12: ^3.3.4
  chalk: ^5.6.2
  copyfiles: ^2.4.1
  defu: ^6.1.7
  eslint: ^10.10.0
  eslint-flat-config-utils: ^3.2.0
  fast-glob: ^3.3.3
  jiti: ^2.7.0
  json5: ^2.2.3
  jsonc-eslint-parser: ^3.3.0
  lefthook: ^2.1.14
  log4brains: ^1.1.0
  nx: 23.1.0
  pkg-types: ^2.3.3
  prettier: ^3.9.7
  rimraf: ^6.1.3
  shadcn: ^4.21.0
  smol-toml: ^1.8.0
  style-dictionary: ^5.5.3
  tailwindcss: ^4.3.3
  tsconfig-paths: ^4.2.0
  untyped: ^2.0.0
  verdaccio: 6.0.5
  vite: ^8.3.0
  vitest: ~4.1.11
  yaml: ^2.9.1
  zod: ^4.6.5
  zx: ^8.8.5
  powerlines: ^0.47.212
  "@storm-software/tsdoc": ^0.13.290
overrides:
  "@emnapi/core": 1.11.2
  "@emnapi/runtime": 1.11.2
  cookie: ">=0.7.0"
fetchTimeout: 240000
cleanupUnusedCatalogs: true
catalogMode: strict
linkWorkspacePackages: true
engineStrict: true
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
  nx: true
  unrs-resolver: true
