/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";
import type { VivaldiTheme } from "./types";

/**
 * Build Vivaldi INSTALL.md for generated theme folders.
 *
 * Steps mirror [Dracula for Vivaldi](https://draculatheme.com/vivaldi): zip each
 * theme folder, then import via **Settings → Themes → Open Theme…**.
 */
export function renderInstallMd(options: {
  themes: Array<{
    name: string;
    displayName: string;
    folderName: string;
    backgroundImage?: string;
  }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1 ? primary.displayName : "Vivaldi Themes");

  const fileList = options.themes
    .map(theme => {
      const files = [`\`${theme.folderName}/settings.json\``];
      if (theme.backgroundImage) {
        files.push(`\`${theme.folderName}/${theme.backgroundImage}\` (add before zipping)`);
      }
      return `- ${files.join(" + ")} — ${theme.displayName}`;
    })
    .join("\n");

  const themeChoices = options.themes
    .map(theme => `- **${theme.displayName}** — folder \`${theme.folderName}/\``)
    .join("\n");

  const backgroundNote = options.themes.some(theme => theme.backgroundImage)
    ? `
If a theme references a background image, copy your image into the theme folder
using the filename from \`settings.json\` (for example \`background.png\`)
before creating the ZIP.
`
    : "";

  return `# Installing ${displayName}

Generated by \`@razorwind/vivaldi\`.

These themes target [Vivaldi](https://vivaldi.com/). Install steps follow the
same pattern as [Dracula for Vivaldi](https://draculatheme.com/vivaldi).

## Files

${fileList}
${backgroundNote}
## Setup

1. Create a ZIP archive for each theme folder (the archive root must contain
   \`settings.json\`, not the parent directory):

\`\`\`sh
cd ${primary.folderName}
zip -r ../${primary.folderName}.zip .
\`\`\`

2. Open Vivaldi **Settings → Themes** (Linux/Windows: **Tools → Settings**, or
   press \`Ctrl+F12\`; macOS: **Vivaldi → Settings → Themes**, or \`⌘,\`).

3. Click **Open Theme…** and select the ZIP file.

4. Confirm **Install** or **Update** in the preview dialog.

## Select / load theme

After import, pick the theme in **Settings → Themes**:

${themeChoices}
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: VivaldiTheme): string {
  return resolveThemeDisplayName(theme);
}
