/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { DesignSystemSnapshot } from "./runtime/records";
import type { DesignSystemCommandId } from "./types";

/** Module specifier the generated commands import runtime helpers from. */
export const RUNTIME_MODULE = "@razorwind/shell-shock/runtime";

/** Directory (under the Shell Shock entry path) holding shared modules. */
export const SHARED_DIRECTORY = "razorwind";

/** File name of the generated design-system snapshot module. */
export const SNAPSHOT_MODULE = "design-system";

/**
 * Static metadata for a contributed design-system command.
 */
export interface DesignSystemCommand {
  id: DesignSystemCommandId;
  title: string;
  description: string;
  icon: string;
  alias?: string[];
  tags: string[];
  /** Render the `command.ts` source. */
  render: (context: CommandRenderContext) => string;
}

export interface CommandRenderContext {
  /** Relative import specifier for the snapshot module. */
  snapshotImport: string;
  /** Design-system title for help / tool descriptions. */
  title: string;
}

const GENERATED_HEADER = `/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

// Generated by @razorwind/shell-shock
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.
`;

const PRINT_HELPERS = `
function print(result: unknown): void {
  process.stdout.write(\`\${typeof result === "string" ? result : JSON.stringify(result, null, 2)}\\n\`);
}
`;

function searchCommandSource(
  context: CommandRenderContext,
  options: {
    interfaceName: string;
    fn: string;
    subject: string;
    example: string;
    extraOptions?: string;
    extraArgs?: string;
  }
): string {
  return `${GENERATED_HEADER}
import { ${options.fn}, isSearchError } from "${RUNTIME_MODULE}";
import { designSystem } from "${context.snapshotImport}";

/**
 * Options for the \`${options.subject}\` search.
 */
export interface ${options.interfaceName} {
  /**
   * One or more search terms (fuzzy match). Example: ${options.example}.
   */
  terms: string[];

  /**
   * Maximum matches per term.
   *
   * @defaultValue 2
   */
  limit?: number;
${options.extraOptions ?? ""}}
${PRINT_HELPERS}
/**
 * Search the ${context.title} ${options.subject} and print matching records as JSON.
 */
export default async function handler(options: ${options.interfaceName}) {
  const result = ${options.fn}(designSystem, {
    terms: options.terms ?? [],
    limit: options.limit${options.extraArgs ?? ""}
  });

  print(result);
  if (isSearchError(result)) {
    process.exitCode = 1;
  }
}
`;
}

function listCommandSource(
  context: CommandRenderContext,
  options: { fn: string; subject: string }
): string {
  return `${GENERATED_HEADER}
import { ${options.fn} } from "${RUNTIME_MODULE}";
import { designSystem } from "${context.snapshotImport}";
${PRINT_HELPERS}
/**
 * Print every ${context.title} ${options.subject} record as JSON.
 */
export default async function handler() {
  print(${options.fn}(designSystem));
}
`;
}

/**
 * All design-system commands contributed by the Shell Shock plugin, in the
 * order they are registered.
 */
export const DESIGN_SYSTEM_COMMANDS: DesignSystemCommand[] = [
  {
    id: "search-tokens",
    title: "Search Tokens",
    description:
      "Search design tokens by name, path, description, type and value. Returns compact JSON records with name and value for each match; set --include-metadata for descriptions and CSS variables.",
    icon: "🎨",
    tags: ["Design System", "Tokens"],
    render: context =>
      searchCommandSource(context, {
        interfaceName: "SearchTokensOptions",
        fn: "searchTokens",
        subject: "design tokens",
        example: '["spacing", "color.text", "background"]',
        extraOptions: `
  /**
   * Include type, description, hex value and CSS variable in each result.
   *
   * @defaultValue false
   */
  includeMetadata?: boolean;
`,
        extraArgs: ",\n    includeMetadata: options.includeMetadata"
      })
  },
  {
    id: "list-tokens",
    title: "List Tokens",
    description:
      "Return every design token (name, value, type, description, CSS variable). Large output - prefer search-tokens for normal use.",
    icon: "🎨",
    tags: ["Design System", "Tokens"],
    render: context =>
      listCommandSource(context, { fn: "listTokens", subject: "design token" })
  },
  {
    id: "search-components",
    title: "Search Components",
    description:
      "Search design-system components by name, title, category, description and tags. Returns name, files, dependencies and usage examples for each match.",
    icon: "🧩",
    tags: ["Design System", "Components"],
    render: context =>
      searchCommandSource(context, {
        interfaceName: "SearchComponentsOptions",
        fn: "searchComponents",
        subject: "components",
        example: '["button", "modal", "select"]'
      })
  },
  {
    id: "list-components",
    title: "List Components",
    description:
      "Return every design-system component record. Large output - prefer search-components for normal use.",
    icon: "🧩",
    tags: ["Design System", "Components"],
    render: context =>
      listCommandSource(context, {
        fn: "listComponents",
        subject: "component"
      })
  },
  {
    id: "search-icons",
    title: "Search Icons",
    description:
      "Search design-system icons by name, title, aliases, tags and category. Returns name and asset files for each match.",
    icon: "🖼",
    tags: ["Design System", "Icons"],
    render: context =>
      searchCommandSource(context, {
        interfaceName: "SearchIconsOptions",
        fn: "searchIcons",
        subject: "icons",
        example: '["search", "folder", "user"]'
      })
  },
  {
    id: "list-icons",
    title: "List Icons",
    description:
      "Return every design-system icon record. Large output - prefer search-icons for normal use.",
    icon: "🖼",
    tags: ["Design System", "Icons"],
    render: context =>
      listCommandSource(context, { fn: "listIcons", subject: "icon" })
  },
  {
    id: "search-fonts",
    title: "Search Fonts",
    description:
      "Search design-system fonts by name, family, role, tags and category. Returns the CSS font-family stack, weights and files for each match.",
    icon: "🔤",
    tags: ["Design System", "Fonts"],
    render: context =>
      searchCommandSource(context, {
        interfaceName: "SearchFontsOptions",
        fn: "searchFonts",
        subject: "fonts",
        example: '["heading", "mono", "inter"]'
      })
  },
  {
    id: "list-fonts",
    title: "List Fonts",
    description: "Return every design-system font record.",
    icon: "🔤",
    tags: ["Design System", "Fonts"],
    render: context =>
      listCommandSource(context, { fn: "listFonts", subject: "font" })
  },
  {
    id: "plan",
    title: "Plan",
    description:
      "Search tokens, icons, components and fonts in one call to plan what to build. Provide terms for at least one list.",
    icon: "🗺",
    tags: ["Design System"],
    render: context => `${GENERATED_HEADER}
import { plan, isSearchError } from "${RUNTIME_MODULE}";
import { designSystem } from "${context.snapshotImport}";

/**
 * Options for the \`plan\` command.
 */
export interface PlanOptions {
  /**
   * Search terms for design tokens. Prefer at least two terms when known.
   */
  tokens?: string[];

  /**
   * Search terms for icons.
   */
  icons?: string[];

  /**
   * Search terms for components.
   */
  components?: string[];

  /**
   * Search terms for fonts.
   */
  fonts?: string[];

  /**
   * Maximum matches per term for each list.
   *
   * @defaultValue 2
   */
  limit?: number;
}
${PRINT_HELPERS}
/**
 * Search the ${context.title} tokens, icons, components and fonts in one pass.
 */
export default async function handler(options: PlanOptions) {
  const result = plan(designSystem, {
    tokens: options.tokens,
    icons: options.icons,
    components: options.components,
    fonts: options.fonts,
    limit: options.limit
  });

  print(result);
  if (isSearchError(result)) {
    process.exitCode = 1;
  }
}
`
  },
  {
    id: "guidelines",
    title: "Guidelines",
    description:
      "Return design-system guidelines as Markdown: an overview of the token groups, one section per component (with usage examples), typography, the design-system style guidelines, and any bundled guideline documents. Pass --terms to search; omit for the full set.",
    icon: "📖",
    tags: ["Design System", "Docs"],
    render: context => `${GENERATED_HEADER}
import { getGuidelines } from "${RUNTIME_MODULE}";
import { designSystem } from "${context.snapshotImport}";

/**
 * Options for the \`guidelines\` command.
 */
export interface GuidelinesOptions {
  /**
   * Search terms matched against guideline keywords, titles and body (fuzzy). Omit to return all guidelines.
   */
  terms?: string[];

  /**
   * Maximum matches per term when searching.
   *
   * @defaultValue 1
   */
  limit?: number;
}
${PRINT_HELPERS}
/**
 * Print ${context.title} guidelines as Markdown.
 */
export default async function handler(options: GuidelinesOptions) {
  print(getGuidelines(designSystem, { terms: options.terms, limit: options.limit }));
}
`
  },
  {
    id: "analyze-a11y",
    title: "Analyze Accessibility",
    description:
      "Analyze a React/JSX source string (or file) for likely accessibility issues and hard-coded colors, suggesting the nearest design tokens for each color.",
    icon: "♿",
    tags: ["Design System", "Accessibility"],
    render: context => `${GENERATED_HEADER}
import { analyzeA11y } from "${RUNTIME_MODULE}";
import { readFile } from "node:fs/promises";
import { designSystem } from "${context.snapshotImport}";

/**
 * Options for the \`analyze-a11y\` command.
 */
export interface AnalyzeA11yOptions {
  /**
   * Source code of a React component or JSX snippet to analyze.
   */
  code?: string;

  /**
   * Path to a source file to analyze (alternative to --code).
   */
  file?: string;

  /**
   * Optional label for the component under review.
   */
  componentName?: string;

  /**
   * Optional usage context (for example "in a form" or "modal").
   */
  context?: string;

  /**
   * Run regex-based heuristics (unlabeled buttons, missing alt, …).
   *
   * @defaultValue true
   */
  patternAnalysis?: boolean;
}
${PRINT_HELPERS}
/**
 * Analyze source code for accessibility issues against the ${context.title} design system.
 */
export default async function handler(options: AnalyzeA11yOptions) {
  const code =
    options.code ?? (options.file ? await readFile(options.file, "utf8") : undefined);
  if (!code) {
    print({ error: "Provide source code via --code or a path via --file." });
    process.exitCode = 1;
    return;
  }

  print(
    analyzeA11y(designSystem, code, {
      componentName: options.componentName,
      context: options.context,
      includePatternAnalysis: options.patternAnalysis !== false
    })
  );
}
`
  }
];

/**
 * Render the shared snapshot module that bakes the design system into the
 * build. `JSON.parse` of a string literal keeps the module cheap to compile
 * even for large design systems.
 */
export function renderSnapshotModule(snapshot: DesignSystemSnapshot): string {
  const json = JSON.stringify(JSON.stringify(snapshot));

  return `${GENERATED_HEADER}
import type { DesignSystemSnapshot } from "${RUNTIME_MODULE}";

/**
 * The extracted design system baked into this CLI at build time.
 */
export const designSystem: DesignSystemSnapshot = Object.freeze(
  JSON.parse(${json})
) as DesignSystemSnapshot;
`;
}

/**
 * Resolve which commands are enabled from the plugin `commands` option.
 */
export function selectCommands(
  commands:
    | DesignSystemCommandId[]
    | Partial<Record<DesignSystemCommandId, boolean>>
    | undefined
): DesignSystemCommand[] {
  if (!commands) {
    return DESIGN_SYSTEM_COMMANDS;
  }
  if (Array.isArray(commands)) {
    const ids = new Set(commands);

    return DESIGN_SYSTEM_COMMANDS.filter(command => ids.has(command.id));
  }

  return DESIGN_SYSTEM_COMMANDS.filter(
    command => commands[command.id] !== false
  );
}
