/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { Schema } from "@razorwind/core/schema";
import { resolveSchemaIdentity, titleCase } from "@razorwind/core/utils";
import type { ShellShockPluginOptions } from "./types";

export interface InstallThemeMeta {
  /** Theme id. */
  name: string;
  /** Generated theme file name (relative to the output directory). */
  fileName: string;
}

/**
 * Render the `INSTALL.md` guide written next to generated Shell Shock files.
 */
export function renderInstallMd(
  spec: Schema,
  themes: InstallThemeMeta[],
  options: ShellShockPluginOptions,
  snapshotFileName?: string
): string {
  if (options.installGuide) {
    return options.installGuide.endsWith("\n")
      ? options.installGuide
      : `${options.installGuide}\n`;
  }

  const title = resolveSchemaIdentity(spec).title ?? "Design System";
  const first = themes[0];
  const sections: string[] = [
    `# Installing the ${title} Shell Shock theme`,
    "",
    "Generated by `@razorwind/shell-shock`.",
    "",
    "## Files",
    "",
    ...themes.map(
      theme =>
        `- \`${theme.fileName}\` — Shell Shock theme config for \`${titleCase(theme.name)}\``
    ),
    ...(snapshotFileName
      ? [
          `- \`${snapshotFileName}\` — snapshot of the extracted design system (tokens, components, icons, fonts) for the Shell Shock plugin`
        ]
      : []),
    "",
    "## Setup",
    "",
    "1. Add the plugin packages to the Shell Shock project:",
    "",
    "   ```bash",
    "   pnpm add @razorwind/shell-shock @shell-shock/plugin-theme @shell-shock/plugin-mcp",
    "   ```",
    "",
    "2. Register the Shell Shock plugin in `shell-shock.config.ts`. It applies the theme, adds design-system commands, and exposes them as MCP tools:",
    "",
    "   ```ts",
    '   import { defineConfig } from "@shell-shock/core/config";',
    '   import preset from "@shell-shock/preset-cli";',
    '   import razorwind from "@razorwind/shell-shock/plugin";',
    "",
    "   export default defineConfig({",
    "     // ...",
    "     plugins: [",
    "       preset(),",
    "       razorwind({",
    ...(snapshotFileName
      ? [`         specFile: "./${snapshotFileName}"`]
      : ['         root: "."']),
    "       })",
    "     ]",
    "   });",
    "   ```",
    ""
  ];

  if (first) {
    sections.push(
      "## Use the theme file directly",
      "",
      "To apply only the theme (without the design-system commands), load the generated JSON into the `theme` option consumed by `@shell-shock/plugin-theme` / `@shell-shock/preset-cli`:",
      "",
      "   ```ts",
      `   import theme from "./${first.fileName}" with { type: "json" };`,
      "",
      "   export default defineConfig({",
      "     plugins: [preset({ theme })]",
      "   });",
      "   ```",
      ""
    );
  }

  sections.push(
    "## MCP",
    "",
    "After building the CLI, start the MCP server with the `mcp` command (name configurable via the `mcp.command` option) and point your MCP client at it:",
    "",
    "   ```json",
    "   {",
    '     "mcpServers": {',
    `       "${resolveSchemaIdentity(spec).name ?? "design-system"}": {`,
    '         "command": "<your-cli-bin>",',
    '         "args": ["mcp"]',
    "       }",
    "     }",
    "   }",
    "   ```",
    "",
    "Each design-system command (`search-tokens`, `list-tokens`, `search-components`, `list-components`, `search-icons`, `list-icons`, `search-fonts`, `list-fonts`, `plan`, `guidelines`, `analyze-a11y`) is exposed as a tool with the same name using `_` separators.",
    ""
  );

  return sections.join("\n");
}
