/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.


 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { NotepadPlusPlusTheme } from "./types";
import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";

/**
 * Build Notepad++ INSTALL.md for generated `*.xml` theme files.
 *
 * Steps mirror [Dracula for Notepad++](https://draculatheme.com/notepad-plus-plus).
 */
export function renderInstallMd(options: {
  themes: Array<{ name: string; displayName: string; fileName: string }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1
      ? primary.displayName
      : "Notepad++ Themes");

  const fileList = options.themes
    .map(theme => `- \`${theme.fileName}\` — ${theme.displayName}`)
    .join("\n");

  const themeChoices = options.themes
    .map(theme => `- **${theme.displayName}** (\`${theme.fileName}\`)`)
    .join("\n");

  return `# Installing ${displayName}

Generated by \`@razorwind/notepad-plus-plus\`.

These themes target [Notepad++](https://notepad-plus-plus.org/). Install steps
follow [Dracula for Notepad++](https://draculatheme.com/notepad-plus-plus).

## Files

${fileList}

## Setup

1. Open your Notepad++ themes folder:

   - Press \`Win + R\`, type \`%AppData%\\Notepad++\\themes\`, press Enter
   - Or navigate to \`C:\\Users\\YourUsername\\AppData\\Roaming\\Notepad++\\themes\`
   - For portable installs, use the \`themes\` folder inside your Notepad++ directory

2. Copy the theme XML file(s) into that folder.

3. Restart Notepad++.

4. Go to **Settings → Style Configurator → Theme**, select your theme from the
   dropdown, then click **Save & Close**.

Available themes:

${themeChoices}

## Select / load theme

The theme name in Style Configurator matches the XML filename without the
\`.xml\` extension (e.g. \`${primary.fileName}\` → **${primary.displayName}**).

If the editor still looks like the default scheme, confirm the theme is selected
(not **Default**) and that Notepad++ was restarted after copying the file.

## Tab colors

If tab text or backgrounds look wrong, check:

1. **Settings → Preferences → General → Tab Bar** — enable **Change inactive tab color**
2. **Settings → Preferences → Dark Mode** — newer builds may override theme tab colors
3. Advanced \`config.xml\` — set \`darkTabUseTheme\` / \`lightModeUseTheme\` so tabs follow the theme
`;
}

export function themeDisplayName(theme: NotepadPlusPlusTheme): string {
  return resolveThemeDisplayName(theme);
}
