/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import type { Schema } from "@razorwind/core/schema";
import {
  createDocument,
  isObject,
  resolveSchemaIdentity,
  slugifyThemeName,
  titleCase,
  type SchemaIdentity
} from "@razorwind/core/utils";
import { join } from "node:path";
import { renderInstallMd, renderPackageReadme } from "./scripts";
import type { ZedPluginOptions, ZedTheme, ZedThemeVariant } from "./types";

const PLUGIN_META = { name: "razorwind-zed" } as const;

const DEFAULT_THEME_SCHEMA = "https://zed.dev/schema/themes/v0.2.0.json";

function document(
  path: string,
  content: string,
  language?: string
): GeneratorFunctionResult<Schema, ZedPluginOptions>[string] {
  return createDocument<Schema, ZedPluginOptions>(
    path,
    content,
    PLUGIN_META,
    language
  );
}

function isZedThemeVariant(value: unknown): value is ZedThemeVariant {
  return (
    isObject(value) &&
    typeof value.name === "string" &&
    (value.appearance === "dark" || value.appearance === "light") &&
    isObject(value.style)
  );
}

function isZedTheme(value: unknown): value is ZedTheme {
  return (
    isObject(value) &&
    typeof value.name === "string" &&
    Array.isArray(value.themes) &&
    value.themes.length > 0 &&
    value.themes.every(isZedThemeVariant)
  );
}

/**
 * Normalize {@link ZedPluginOptions.mapTheme} results into a theme list.
 */
export function normalizeThemes(
  result: ZedTheme | ZedTheme[] | Record<string, ZedTheme>
): ZedTheme[] {
  if (Array.isArray(result)) {
    return result.map((theme, index) => {
      if (!isZedTheme(theme)) {
        throw new TypeError(
          `@razorwind/zed mapTheme()[${index}] must be a ZedTheme with name + themes[]`
        );
      }
      return theme;
    });
  }

  if (isZedTheme(result)) {
    return [result];
  }

  if (!isObject(result)) {
    throw new TypeError(
      "@razorwind/zed mapTheme() must return a theme, theme array, or theme record"
    );
  }

  return Object.entries(result).map(([key, theme]) => {
    if (!isZedTheme(theme)) {
      throw new TypeError(
        `@razorwind/zed mapTheme()["${key}"] must be a ZedTheme with name + themes[]`
      );
    }
    return {
      ...theme,
      name: theme.name || key
    };
  });
}

function assertOptions(
  options: ZedPluginOptions
): asserts options is ZedPluginOptions & {
  mapTheme: NonNullable<ZedPluginOptions["mapTheme"]>;
  id: string;
} {
  if (!options.mapTheme) {
    throw new Error("@razorwind/zed requires options.mapTheme");
  }
  if (!options.id || options.id.includes("/")) {
    throw new Error(
      "@razorwind/zed requires options.id (unscoped extension id slug)"
    );
  }
}

function escapeTomlString(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

/**
 * Serialize a Zed theme collection document for `themes/*.json`.
 *
 * @see https://zed.dev/schema/themes/v0.2.0.json
 */
export function renderThemeJson(
  theme: ZedTheme,
  defaultSchema = DEFAULT_THEME_SCHEMA
): string {
  const payload: Record<string, unknown> = {
    $schema: theme.$schema ?? defaultSchema,
    name: theme.name,
    themes: theme.themes
  };

  if (theme.author) {
    payload.author = theme.author;
  }

  return `${JSON.stringify(payload, null, 2)}\n`;
}

/**
 * Build the Zed extension `extension.toml` manifest.
 */
export function renderExtensionToml(
  options: ZedPluginOptions,
  spec: SchemaIdentity = {}
): string {
  const identity = resolveSchemaIdentity(spec, {
    title: options.name,
    description: options.description,
    repository: options.repository
  });
  const displayName = identity.title ?? titleCase(options.id);
  const description =
    identity.description ??
    `${displayName} — Zed themes generated by Razorwind`;
  const repository = options.repository ?? identity.repository;

  const lines = [
    `id = "${escapeTomlString(options.id)}"`,
    `name = "${escapeTomlString(displayName)}"`,
    `version = "${escapeTomlString(options.version ?? "0.0.1")}"`,
    `schema_version = ${options.schemaVersion ?? 1}`,
    `description = "${escapeTomlString(description)}"`
  ];

  if (options.authors?.length) {
    const authors = options.authors
      .map(author => `"${escapeTomlString(author)}"`)
      .join(", ");
    lines.push(`authors = [${authors}]`);
  }

  if (repository) {
    lines.push(`repository = "${escapeTomlString(repository)}"`);
  }

  return `${lines.join("\n")}\n`;
}

export { renderInstallMd };

/**
 * Generate a Zed-installable theme extension package from a Razorwind schema.
 *
 * Emits theme collection JSON, `extension.toml`, `README.md`, and `INSTALL.md`.
 *
 * @see https://draculatheme.com/zed
 */
export function generateZedExtension(
  spec: Schema,
  options: ZedPluginOptions
): GeneratorFunctionResult<Schema, ZedPluginOptions> {
  assertOptions(options);

  const outputPath = options.outputPath ?? "zed-extension";
  const identity = resolveSchemaIdentity(spec, {
    title: options.name,
    description: options.description,
    repository: options.repository
  });
  const displayName = identity.title ?? titleCase(options.id);
  const description =
    identity.description ??
    `${displayName} — Zed themes generated by Razorwind`;
  const repository = options.repository ?? identity.repository;
  const defaultSchema = options.themeSchema ?? DEFAULT_THEME_SCHEMA;

  const themes = normalizeThemes(options.mapTheme(spec.tokens));
  if (themes.length === 0) {
    throw new Error("@razorwind/zed mapTheme() returned no themes");
  }

  const documents: GeneratorFunctionResult<Schema, ZedPluginOptions> = {};
  const usedSlugs = new Set<string>();
  const themeMeta: Array<{
    label: string;
    path: string;
    slug: string;
    fileName: string;
  }> = [];

  for (const theme of themes) {
    let slug = slugifyThemeName(theme.name);
    if (usedSlugs.has(slug)) {
      let suffix = 2;
      while (usedSlugs.has(`${slugifyThemeName(theme.name)}-${suffix}`)) {
        suffix += 1;
      }
      slug = `${slugifyThemeName(theme.name)}-${suffix}`;
    }
    usedSlugs.add(slug);

    const fileName = `${slug}.json`;
    const themePath = join(outputPath, "themes", fileName);
    documents[themePath] = document(
      themePath,
      renderThemeJson(theme, defaultSchema),
      "json"
    );

    for (const variant of theme.themes) {
      themeMeta.push({
        label: variant.name,
        path: `themes/${fileName}`,
        slug,
        fileName
      });
    }
  }

  const extensionTomlPath = join(outputPath, "extension.toml");
  documents[extensionTomlPath] = document(
    extensionTomlPath,
    renderExtensionToml(options, spec),
    "toml"
  );

  const themeLabels = themeMeta.map(theme => ({ label: theme.label }));
  const readmeBody =
    options.readme ??
    renderPackageReadme({
      displayName,
      description,
      themes: themeLabels,
      repositoryUrl: repository
    });

  const readmePath = join(outputPath, "README.md");
  documents[readmePath] = document(readmePath, readmeBody, "markdown");

  const installBody =
    options.installGuide ??
    renderInstallMd({
      displayName,
      extensionId: options.id,
      themes: themeMeta
    });

  const installPath = join(outputPath, "INSTALL.md");
  documents[installPath] = document(installPath, installBody, "markdown");

  return documents;
}
