/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Templates for Zed extension install docs.
 *
 * @see https://draculatheme.com/zed
 * @see https://github.com/dracula/zed
 */

export function renderPackageReadme(options: {
  displayName: string;
  description: string;
  themes: Array<{ label: string }>;
  repositoryUrl?: string;
}): string {
  const themeList = options.themes.map(theme => `- ${theme.label}`).join("\n");

  const links = options.repositoryUrl
    ? `\n## Links\n\n- [GitHub](${options.repositoryUrl})\n`
    : "";

  return `# ${options.displayName}

${options.description}

## Installation

See **INSTALL.md** for Zed extension store and manual theme install steps.

## Themes

${themeList || "- (generated themes)"}
${links}`;
}

/**
 * Zed-specific install guide (extensions store + manual copy).
 *
 * @see https://draculatheme.com/zed
 */
export function renderInstallMd(options: {
  displayName: string;
  extensionId: string;
  themes: Array<{ label: string; path: string; fileName: string }>;
}): string {
  const themeFiles = options.themes
    .map(theme => `- \`${theme.path}\` — ${theme.label}`)
    .join("\n");
  const themeLabels = options.themes
    .map(theme => `- **${theme.label}**`)
    .join("\n");
  const manualFiles = options.themes
    .map(theme => `- \`${theme.fileName}\``)
    .join("\n");

  return `# Installing ${options.displayName}

Generated by \`@razorwind/zed\`.

## Files

- \`extension.toml\` — Zed extension manifest
- \`themes/*.json\` — Zed theme collection documents
${themeFiles}

## Install in Zed (extensions store)

1. Open Zed and open the extensions panel.
2. Search for **${options.displayName}** (extension id: \`${options.extensionId}\`) or publish this folder as a Zed extension.
3. After installing, open **Settings → Select Theme** and pick a variant:

${themeLabels}

## Install manually

Copy theme JSON into Zed's themes directory:

\`\`\`bash
mkdir -p ~/.config/zed/themes
cp themes/*.json ~/.config/zed/themes/
\`\`\`

Files:

${manualFiles}

Then open **Settings → Select Theme** and choose a variant listed above.

## Select theme

\`Settings → Select Theme\` → pick a variant label from this extension.
`;
}
