/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build docgen INSTALL.md for generated MDX documentation.
 */
export function renderInstallMd(options: {
  outDir: string;
  title?: string;
}): string {
  const title = options.title ?? "Design System";

  return `# Installing ${title} Docs

Generated by \`@razorwind/docgen\`.

## Files

- \`${options.outDir}/index.mdx\` — documentation index
- \`${options.outDir}/tokens/\` — per-group token pages
- \`${options.outDir}/tokens.json\` — flattened token manifest

## Setup

1. Wire generated MDX into your docs site (Storybook, Nextra, Docusaurus, etc.).

Example for Storybook:

\`\`\`ts
// .storybook/main.ts
export default {
  stories: ["../${options.outDir}/**/*.mdx"]
};
\`\`\`

2. Open \`${options.outDir}/index.mdx\` as the **${title}** entry point.

3. Re-run Razorwind generate when tokens or registry items change.

## Regenerate

Docs under \`${options.outDir}/\` are generated output — edit source tokens/components instead of hand-editing MDX.
`;
}
