/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import { definePlugin } from "@razorwind/core/plugin";
import type { Fonts, Schema } from "@razorwind/core/schema";
import { createDocument } from "@razorwind/core/utils";
import { dirname, join } from "node:path";
import { flattenThemeTokens, resolveTokenSets } from "./generate";
import type {
  FlatThemeToken,
  GuardrailTheme,
  TailwindEslintPluginOptions
} from "./types";

export type {
  GuardrailOptions,
  GuardrailRuleId,
  GuardrailSeverity,
  GuardrailTheme,
  TailwindEslintPluginOptions
} from "./types";

const DEFAULT_ESLINT_PATH = "eslint/razorwind-guardrails.mjs";
const DEFAULT_PREFIX = "design-system";
const DEFAULT_RUNTIME_IMPORT = "@razorwind/tailwindcss/eslint-runtime";

/**
 * Tailwind v4 `@theme` namespaces, longest first so `--font-weight-*` is not
 * read as `--font-*`.
 *
 * @see https://tailwindcss.com/docs/theme#theme-variable-namespaces
 */
export const TAILWIND_THEME_NAMESPACES = [
  "inset-shadow",
  "drop-shadow",
  "text-shadow",
  "font-weight",
  "breakpoint",
  "container",
  "perspective",
  "tracking",
  "leading",
  "spacing",
  "animate",
  "aspect",
  "radius",
  "shadow",
  "color",
  "font",
  "text",
  "blur",
  "ease"
] as const;

/**
 * Split a Tailwind theme custom property into its namespace and name.
 *
 * @example
 * splitThemeCssVar("--color-neutral-800") // ["color", "neutral-800"]
 * splitThemeCssVar("--radius") // ["radius", ""]
 */
export function splitThemeCssVar(
  cssVar: string
): [namespace: string, name: string] | undefined {
  const bare = cssVar.replace(/^--/, "");
  for (const ns of TAILWIND_THEME_NAMESPACES) {
    if (bare === ns) {
      return [ns, ""];
    }
    if (bare.startsWith(`${ns}-`)) {
      const name = bare.slice(ns.length + 1);
      // `--text-sm--line-height` style sub-properties are not utilities.
      return name.includes("--") ? undefined : [ns, name];
    }
  }

  return undefined;
}

/**
 * Build the guardrail theme manifest from flattened `@theme` tokens: every
 * Tailwind namespace the schema defines, with the names it defines.
 */
export function buildGuardrailTheme(
  tokens: FlatThemeToken[],
  options: {
    fonts?: Fonts;
    name?: string;
    version?: string;
    prefix?: string;
  } = {}
): GuardrailTheme {
  const namespaces = new Map<string, Set<string>>();
  const add = (cssVar: string) => {
    const parts = splitThemeCssVar(cssVar);
    if (!parts) {
      return;
    }
    const names = namespaces.get(parts[0]) ?? new Set<string>();
    names.add(parts[1]);
    namespaces.set(parts[0], names);
  };

  for (const token of tokens) {
    add(token.cssVar);
  }
  // Mirrors the CSS generator, which emits `--font-<role>` for schema fonts.
  for (const font of Object.values(options.fonts ?? {})) {
    if (font.role) {
      add(`--font-${font.role}`);
    }
  }

  const themes = [
    ...new Set(
      tokens.map(token => token.theme).filter((id): id is string => !!id)
    )
  ].sort();

  return {
    name: options.name ?? DEFAULT_PREFIX,
    version: options.version ?? "0.0.0",
    prefix: options.prefix ?? DEFAULT_PREFIX,
    themes,
    namespaces: Object.fromEntries(
      [...namespaces.entries()]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([ns, names]) => [
          ns,
          [...names].sort((a, b) =>
            a.localeCompare(b, undefined, { numeric: true })
          )
        ])
    )
  };
}

/**
 * Render the ESLint plugin module that binds the guardrail runtime to the
 * schema-derived theme.
 */
export function renderEslintPlugin(
  theme: GuardrailTheme,
  options: Pick<TailwindEslintPluginOptions, "runtimeImport"> = {}
): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;

  return `// Generated by @razorwind/tailwindcss. Do not edit by hand: re-run
// Razorwind generate when design tokens change.
//
//   import guardrails from "./<path-to-this-file>";
//   export default [
//     ...,
//     guardrails({ files: ["src/**/*.{ts,tsx}"] })
//   ];

import { createGuardrails } from ${JSON.stringify(runtimeImport)};

export const theme = ${JSON.stringify(theme, null, 2)};

const guardrails = createGuardrails(theme);

export const plugin = guardrails.plugin;
export const rules = guardrails.rules;
export const defaultSeverity = guardrails.defaultSeverity;

export default guardrails.config;
`;
}

/**
 * Build ESLint guardrails INSTALL.md for the generated plugin module.
 */
export function renderEslintInstallMd(options: {
  eslintPath: string;
  theme: GuardrailTheme;
}): string {
  const { eslintPath, theme } = options;
  const namespaces = Object.entries(theme.namespaces)
    .map(([ns, names]) => `- \`--${ns}-*\` (${names.length})`)
    .join("\n");

  return `# Installing ESLint Design-System Guardrails

Generated by \`@razorwind/tailwindcss\`.

## Files

- \`${eslintPath}\` — ESLint flat-config plugin whose rules are derived from the design tokens

## Setup

1. Install the runtime the generated module imports:

\`\`\`bash
pnpm add -D @razorwind/tailwindcss
\`\`\`

2. Add the guardrails to \`eslint.config.mjs\`:

\`\`\`js
import guardrails from "./${eslintPath}";

export default [
  // ...
  guardrails({
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/components/pdf/**"],
    severity: { "no-stock-palette": "error" }
  })
];
\`\`\`

3. Deliberate one-offs carry an inline, reviewable exception:

\`\`\`ts
// eslint-disable-next-line ${theme.prefix}/no-color-literal -- <reason>
\`\`\`

## Token namespaces

Rules for a namespace are only enabled when the schema defines it:

${namespaces || "- _(none)_"}

## Regenerate

Re-run Razorwind generate when design tokens change so \`${eslintPath}\` stays in sync.
`;
}

/**
 * Generate an ESLint guardrails plugin aligned with the schema's Tailwind theme.
 */
export async function generateEslintGuardrails(
  spec: Schema,
  options: TailwindEslintPluginOptions = {}
): Promise<GeneratorFunctionResult<Schema, TailwindEslintPluginOptions>> {
  if (!spec.tokens || resolveTokenSets(spec.tokens).length === 0) {
    return {};
  }

  const flat = flattenThemeTokens(spec.tokens);
  if (flat.length === 0) {
    return {};
  }

  const theme = buildGuardrailTheme(flat, {
    fonts: spec.fonts,
    name: spec.name,
    prefix: options.prefix
  });
  const eslintPath = options.eslintPath ?? DEFAULT_ESLINT_PATH;
  const installPath = join(dirname(eslintPath), "INSTALL.md");
  const meta = { name: "razorwind-tailwindcss-eslint" };

  return {
    [eslintPath]: createDocument<Schema, TailwindEslintPluginOptions>(
      eslintPath,
      renderEslintPlugin(theme, options),
      meta,
      undefined,
      "javascript"
    ),
    [installPath]: createDocument<Schema, TailwindEslintPluginOptions>(
      installPath,
      options.installGuide ?? renderEslintInstallMd({ eslintPath, theme }),
      meta,
      undefined,
      "markdown"
    )
  };
}

/**
 * Razorwind plugin: generate an ESLint guardrails plugin that keeps Tailwind
 * class usage aligned with the schema's design tokens.
 *
 * @example
 * ```ts
 * import { defineConfig } from "@razorwind/core";
 * import tailwindcss from "@razorwind/tailwindcss/generate";
 * import tailwindcssEslint from "@razorwind/tailwindcss/eslint";
 *
 * export default defineConfig({
 *   plugins: [tailwindcss(), tailwindcssEslint()]
 * });
 * ```
 */
export default definePlugin((options?: TailwindEslintPluginOptions) => ({
  name: "tailwindcss:eslint",
  generate: async spec => generateEslintGuardrails(spec, options ?? {})
}));
