/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build Tailwind INSTALL.md for generated CSS theme entry.
 *
 * @see https://tailwindcss.com/docs/theme
 */
export function renderInstallMd(options: {
  cssPath: string;
  includeImport: boolean;
}): string {
  const importLine = options.includeImport
    ? "The file includes `@import \"tailwindcss\"` and `@theme` token mappings."
    : "The file contains `@theme` token mappings (no `@import \"tailwindcss\"`).";

  return `# Installing Tailwind Theme CSS

Generated by \`@razorwind/tailwindcss\`.

## Files

- \`${options.cssPath}\` — Tailwind v4 theme entry (${importLine})

## Setup

1. Import the generated CSS in your app entry (or merge into your existing Tailwind entry):

\`\`\`ts
import "./${options.cssPath}";
\`\`\`

2. Ensure your build uses Tailwind v4 (Vite plugin, PostCSS, or CLI).

3. Use generated theme tokens as utilities or arbitrary values, e.g. \`bg-primary\` when \`--color-primary\` is defined in `@theme`.

## Regenerate

Re-run Razorwind generate when design tokens change so \`${options.cssPath}\` stays in sync.
`;
}
