/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import { definePlugin } from "@razorwind/core/plugin";
import type { Schema } from "@razorwind/core/schema";
import { createDocument } from "@razorwind/core/utils";
import { dirname, join } from "node:path";
import { buildGuardrailTheme } from "./eslint";
import { flattenThemeTokens, resolveTokenSets } from "./generate";
import type { GuardrailTheme, TailwindStylelintPluginOptions } from "./types";

export { buildGuardrailTheme, splitThemeCssVar } from "./eslint";
export type {
  GuardrailRuleId,
  GuardrailSeverity,
  GuardrailTheme,
  StylelintGuardrailOptions,
  TailwindStylelintPluginOptions
} from "./types";

const DEFAULT_STYLELINT_PATH = "stylelint/razorwind-guardrails.mjs";
const DEFAULT_RUNTIME_IMPORT = "@razorwind/tailwindcss/stylelint-runtime";

/**
 * Render the Stylelint plugin module that binds the guardrail runtime to the
 * schema-derived theme.
 */
export function renderStylelintPlugin(
  theme: GuardrailTheme,
  options: Pick<TailwindStylelintPluginOptions, "runtimeImport"> = {}
): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;

  return `// Generated by @razorwind/tailwindcss. Do not edit by hand: re-run
// Razorwind generate when design tokens change.
//
//   import guardrails from "./<path-to-this-file>";
//   const { plugins, rules } = guardrails();
//   export default { plugins: [...plugins], rules: { ...rules } };

import { createGuardrails } from ${JSON.stringify(runtimeImport)};

export const theme = ${JSON.stringify(theme, null, 2)};

const guardrails = createGuardrails(theme);

export const plugins = guardrails.plugins;
export const rules = guardrails.rules;
export const defaultSeverity = guardrails.defaultSeverity;

export default guardrails.config;
`;
}

/**
 * Build the Stylelint guardrails INSTALL.md for the generated plugin module.
 */
export function renderStylelintInstallMd(options: {
  stylelintPath: string;
  theme: GuardrailTheme;
}): string {
  const { stylelintPath, theme } = options;
  const namespaces = Object.entries(theme.namespaces)
    .map(([ns, names]) => `- \`--${ns}-*\` (${names.length})`)
    .join("\n");

  return `# Installing Stylelint Design-System Guardrails

Generated by \`@razorwind/tailwindcss\`.

## Files

- \`${stylelintPath}\` — Stylelint plugins whose rules are derived from the design tokens

## Setup

1. Install the runtime the generated module imports:

\`\`\`bash
pnpm add -D @razorwind/tailwindcss stylelint
\`\`\`

2. Add the guardrails to \`stylelint.config.mjs\`:

\`\`\`js
import guardrails from "./${stylelintPath}";

const { plugins, rules } = guardrails({
  severity: { "no-stock-palette": "error" }
});

export default {
  plugins: [...plugins],
  rules: { ...rules }
};
\`\`\`

Class rules read \`@apply\` preludes; \`no-unknown-theme-var\` also reads
\`var()\`, \`theme()\` and \`--theme()\` references in declarations and at-rules.

3. Deliberate one-offs carry an inline, reviewable exception:

\`\`\`css
/* stylelint-disable-next-line ${theme.prefix}/no-color-literal -- <reason> */
\`\`\`

## Token namespaces

Rules for a namespace are only enabled when the schema defines it:

${namespaces || "- _(none)_"}

## Regenerate

Re-run Razorwind generate when design tokens change so \`${stylelintPath}\` stays in sync.
`;
}

/**
 * Generate a Stylelint guardrails plugin aligned with the schema's Tailwind
 * theme.
 */
export async function generateStylelintGuardrails(
  spec: Schema,
  options: TailwindStylelintPluginOptions = {}
): Promise<GeneratorFunctionResult<Schema, TailwindStylelintPluginOptions>> {
  if (!spec.tokens || resolveTokenSets(spec.tokens).length === 0) {
    return {};
  }

  const flat = flattenThemeTokens(spec.tokens);
  if (flat.length === 0) {
    return {};
  }

  const theme = buildGuardrailTheme(flat, {
    fonts: spec.fonts,
    name: spec.name,
    prefix: options.prefix
  });
  const stylelintPath = options.stylelintPath ?? DEFAULT_STYLELINT_PATH;
  const installPath = join(dirname(stylelintPath), "INSTALL.md");
  const meta = { name: "razorwind-tailwindcss-stylelint" };

  return {
    [stylelintPath]: createDocument<Schema, TailwindStylelintPluginOptions>(
      stylelintPath,
      renderStylelintPlugin(theme, options),
      meta,
      undefined,
      "javascript"
    ),
    [installPath]: createDocument<Schema, TailwindStylelintPluginOptions>(
      installPath,
      options.installGuide ??
        renderStylelintInstallMd({ stylelintPath, theme }),
      meta,
      undefined,
      "markdown"
    )
  };
}

/**
 * Razorwind plugin: generate a Stylelint guardrails plugin that keeps
 * `@apply` classes and theme variable references aligned with the schema's
 * design tokens.
 *
 * @example
 * ```ts
 * import { defineConfig } from "@razorwind/core";
 * import tailwindcss from "@razorwind/tailwindcss/generate";
 * import tailwindcssStylelint from "@razorwind/tailwindcss/stylelint";
 *
 * export default defineConfig({
 *   plugins: [tailwindcss(), tailwindcssStylelint()]
 * });
 * ```
 */
export default definePlugin((options?: TailwindStylelintPluginOptions) => ({
  name: "tailwindcss:stylelint",
  generate: async spec => generateStylelintGuardrails(spec, options ?? {})
}));
