/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { SandpackTheme } from "./types";
import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";

/**
 * Build Sandpack INSTALL.md for generated theme and usage files.
 *
 * @see https://sandpack.codesandbox.io/docs/getting-started/themes#custom-theme
 * @see https://sandpack.codesandbox.io/docs/getting-started/usage#files
 */
export function renderInstallMd(options: {
  themes: Array<{ name: string; displayName: string; fileName: string }>;
  usages: Array<{
    name: string;
    displayName: string;
    fileName: string;
    component?: string;
  }>;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.themes.length === 1 ? primary.displayName : "Sandpack Themes";

  const themeList = options.themes
    .map(
      theme =>
        `- \`themes/${theme.fileName}\` — ${theme.displayName} (\`theme\` id: \`${theme.name}\`)`
    )
    .join("\n");

  const usageList =
    options.usages.length > 0
      ? options.usages
          .map(usage => {
            const label = usage.component
              ? `${usage.displayName} (\`${usage.component}\`)`
              : usage.displayName;
            return `- \`usage/${usage.fileName}\` — ${label}`;
          })
          .join("\n")
      : "_No component usage demos were generated._";

  const usageSnippet =
    options.usages.length > 0
      ? `import demo from "./sandpack/usage/${options.usages[0]!.fileName}";

<Sandpack
  template={demo.template}
  files={demo.files}
  theme={theme}
  customSetup={
    demo.dependencies ? { dependencies: demo.dependencies } : undefined
  }
/>`
      : `import { Sandpack } from "@codesandbox/sandpack-react";
import theme from "./sandpack/themes/${primary.fileName}";

<Sandpack theme={theme} template="react" />`;

  return `# Installing ${displayName}

Generated by \`@razorwind/sandpack\`.

These artifacts target [Sandpack](https://sandpack.codesandbox.io/)
(\`@codesandbox/sandpack-react\`).

## Files

### Themes

${themeList}

### Usage demos

${usageList}

## Setup

1. Install Sandpack React:

\`\`\`sh
pnpm add @codesandbox/sandpack-react
\`\`\`

2. Import a generated theme and pass it to \`theme\`:

\`\`\`tsx
import { Sandpack } from "@codesandbox/sandpack-react";
import theme from "./sandpack/themes/${primary.fileName}";

export function Demo() {
  return <Sandpack theme={theme} template="react" />;
}
\`\`\`

Custom themes override the default light theme. See
[Sandpack custom themes](https://sandpack.codesandbox.io/docs/getting-started/themes#custom-theme).

## Select / load usage files

Each usage JSON is shaped for the Sandpack [\`files\` prop](https://sandpack.codesandbox.io/docs/getting-started/usage#files):

\`\`\`tsx
${usageSnippet}
\`\`\`

Available theme ids:

${options.themes.map(theme => `- \`${theme.name}\` (${theme.displayName})`).join("\n")}
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: SandpackTheme): string {
  return resolveThemeDisplayName(theme);
}
