/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build DESIGN.md INSTALL.md for generated design spec file.
 *
 * @see https://github.com/google-labs-code/design.md
 */
export function renderInstallMd(options: {
  outputPath: string;
  name?: string;
}): string {
  const name = options.name ?? "Razorwind Design System";

  return `# Installing ${name} (DESIGN.md)

Generated by \`@razorwind/design-md\`.

## Files

- \`${options.outputPath}\` — DESIGN.md design-system specification

## Setup

1. Place \`${options.outputPath}\` at your repo root (or the path your tooling expects).

2. Point DESIGN.md-aware tools (agents, linters, generators) at this file as the canonical design spec.

3. Keep \`${options.outputPath}\` in sync by re-running Razorwind generate when tokens or components change.

## Usage

Reference token names, component rules, and layout guidance from \`${options.outputPath}\` when implementing UI. Regenerate rather than hand-editing generated sections.
`;
}
