/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.


 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GhosttyTheme } from "./types";
import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";

/**
 * Build Ghostty INSTALL.md for generated theme files.
 *
 * Steps mirror [Dracula for Ghostty](https://draculatheme.com/ghostty): copy
 * into `~/.config/ghostty/themes/`, set `theme =` in `config`, reload.
 */
export function renderInstallMd(options: {
  themes: Array<{ name: string; displayName: string; fileName: string }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1 ? primary.displayName : "Ghostty Themes");

  const fileList = options.themes
    .map(
      theme =>
        `- \`${theme.fileName}\` — ${theme.displayName} (\`theme = ${theme.name}\`)`
    )
    .join("\n");

  const themeChoices = options.themes
    .map(theme => `- \`${theme.name}\` (${theme.displayName})`)
    .join("\n");

  return `# Installing ${displayName}

Generated by \`@razorwind/ghostty\`.

These themes target [Ghostty](https://ghostty.org/). Install steps follow the
same pattern as [Dracula for Ghostty](https://draculatheme.com/ghostty).

## Files

${fileList}

## Setup

1. Copy each theme file into your Ghostty themes directory:

\`\`\`sh
mkdir -p ~/.config/ghostty/themes
cp ${primary.fileName} ~/.config/ghostty/themes/
\`\`\`

2. Add the following line to \`~/.config/ghostty/config\`:

\`\`\`ini
theme = ${primary.name}
\`\`\`

Available theme ids:

${themeChoices}

3. Reload Ghostty to apply the changes.

Alternatively, copy the contents of the theme file directly into \`config\`.

## Select / load theme

\`theme\` must match the theme filename without a path (e.g. \`${primary.fileName}\` → \`theme = ${primary.name}\`).
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: GhosttyTheme): string {
  return resolveThemeDisplayName(theme);
}
