/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import { definePlugin } from "@razorwind/core/plugin";
import type { Schema } from "@razorwind/core/schema";
import { createDocument } from "@razorwind/core/utils";
import { dirname, join } from "node:path";
import { buildManifest } from "./manifest";
import { createDesignSystemPlugin } from "./runtime";
import type {
  DesignSystemManifest,
  DesignSystemRuleId,
  StylelintPluginOptions
} from "./types";

export { buildManifest, DEFAULT_PREFIX } from "./manifest";
export type {
  ComponentRole,
  CoreRuleId,
  DesignSystemManifest,
  DesignSystemOptions,
  DesignSystemRuleId,
  DesignSystemSeverity,
  FallbackUsage,
  ManifestComponent,
  ManifestFont,
  ManifestToken,
  StylelintPluginOptions,
  TokenCategory,
  TokenUsageDomains
} from "./types";

const DEFAULT_STYLELINT_PATH = "stylelint/design-system/index.mjs";
const DEFAULT_RUNTIME_IMPORT = "@razorwind/stylelint/runtime";

/**
 * Render the Stylelint plugin module that binds the design-system runtime to
 * the schema-derived manifest.
 */
export function renderStylelintPlugin(
  manifest: DesignSystemManifest,
  options: Pick<StylelintPluginOptions, "runtimeImport"> = {}
): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;

  return `// Generated by @razorwind/stylelint. Do not edit by hand: re-run
// Razorwind generate when design tokens change.
//
//   import designSystem from "./<path-to-this-file>";
//   const { plugins, rules } = designSystem();
//   export default { plugins: [...plugins], rules: { ...rules } };

import { createDesignSystemPlugin } from ${JSON.stringify(runtimeImport)};

export const manifest = ${JSON.stringify(manifest, null, 2)};

const designSystem = createDesignSystemPlugin(manifest);

export const plugins = designSystem.plugins;
export const rules = designSystem.rules;
export const defaultSeverity = designSystem.defaultSeverity;

export default designSystem.config;
`;
}

/**
 * Build the Stylelint INSTALL.md for the generated plugin module, listing
 * every rule with the default severity the schema gives it.
 */
export function renderStylelintInstallMd(options: {
  stylelintPath: string;
  manifest: DesignSystemManifest;
}): string {
  const { stylelintPath, manifest } = options;
  const { rules, defaultSeverity } = createDesignSystemPlugin(manifest);
  const rows = (Object.keys(rules) as DesignSystemRuleId[])
    .map(id => {
      const rule = rules[id]!;

      return `| \`${rule.ruleName}\` | ${defaultSeverity[id] ?? "off"} | ${rule.meta.description} |`;
    })
    .join("\n");
  const counts = [
    `${manifest.tokens.length} tokens`,
    `${manifest.components.length} components`,
    `${manifest.fonts.length} fonts`
  ].join(", ");

  return `# Installing the Stylelint Design-System Plugin

Generated by \`@razorwind/stylelint\` from ${counts}.

## Files

- \`${stylelintPath}\` — Stylelint plugins whose rules are derived from the design system

## Setup

1. Install the runtime the generated module imports:

\`\`\`bash
pnpm add -D @razorwind/stylelint stylelint
\`\`\`

2. Add the plugins and rules to \`stylelint.config.mjs\`:

\`\`\`js
import designSystem from "./${stylelintPath}";

const { plugins, rules } = designSystem({
  // Domains ensure-design-token-usage checks (colors and shadows by default).
  tokenUsage: { color: true, spacing: true },
  // "forced" requires var(--token, fallback), "none" forbids fallbacks.
  fallbackUsage: "optional",
  severity: { "no-physical-properties": "error" }
});

export default {
  plugins: [...plugins],
  rules: { ...rules }
};
\`\`\`

Passing \`files\` moves the rules into an \`overrides\` entry for those globs.

3. Deliberate one-offs carry an inline, reviewable exception:

\`\`\`css
/* stylelint-disable-next-line ${manifest.prefix}/ensure-design-token-usage -- <reason> */
\`\`\`

## Rules

Token rules are enabled when the design system defines that token category.
Literals that match exactly one token's value are fixed by \`stylelint --fix\`.

| Rule | Default | Description |
| ---- | ------- | ----------- |
${rows}

## Regenerate

Re-run Razorwind generate when the design system changes so \`${stylelintPath}\` stays in sync.
`;
}

/**
 * Generate a Stylelint plugin whose rules are derived from the schema's
 * design tokens, components and fonts.
 */
export async function generateStylelintPlugin(
  spec: Schema,
  options: StylelintPluginOptions = {}
): Promise<GeneratorFunctionResult<Schema, StylelintPluginOptions>> {
  const manifest = buildManifest(spec, options);
  if (manifest.tokens.length === 0 && manifest.components.length === 0) {
    return {};
  }

  const stylelintPath = options.stylelintPath ?? DEFAULT_STYLELINT_PATH;
  const installPath = join(dirname(stylelintPath), "INSTALL.md");
  const meta = { name: "razorwind-stylelint" };

  return {
    [stylelintPath]: createDocument<Schema, StylelintPluginOptions>(
      stylelintPath,
      renderStylelintPlugin(manifest, options),
      meta,
      undefined,
      "javascript"
    ),
    [installPath]: createDocument<Schema, StylelintPluginOptions>(
      installPath,
      options.installGuide ??
        renderStylelintInstallMd({ stylelintPath, manifest }),
      meta,
      undefined,
      "markdown"
    )
  };
}

/**
 * Razorwind plugin: generate a Stylelint plugin that keeps stylesheets
 * aligned with the design system. It ports the
 * `\@atlaskit/stylelint-design-system` rules onto the schema's own tokens,
 * adds the `\@razorwind/eslint` rules that apply to stylesheets, and bundles
 * the `\@razorwind/tailwindcss` guardrails.
 *
 * @example
 * ```ts
 * import { defineConfig } from "@razorwind/core";
 * import stylelint from "@razorwind/stylelint";
 *
 * export default defineConfig({
 *   plugins: [stylelint({ prefix: "acme" })]
 * });
 * ```
 */
export default definePlugin((options?: StylelintPluginOptions) => ({
  name: "stylelint",
  themeGeneration: "combined",
  generate: async spec => generateStylelintPlugin(spec, options ?? {})
}));
