/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";
import type { ThunderbirdTheme } from "./types";

/**
 * Build Thunderbird INSTALL.md for generated extension theme folders.
 *
 * Steps follow loading a theme from the Add-ons manager, as used by community
 * themes such as [Dracula for Thunderbird](https://draculatheme.com/thunderbird).
 */
export function renderInstallMd(options: {
  themes: Array<{
    name: string;
    displayName: string;
    folderName: string;
    iconPaths?: string[];
  }>;
  /** Design-system / package title from Schema when multiple themes. */
  title?: string;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.title ??
    (options.themes.length === 1 ? primary.displayName : "Thunderbird Themes");

  const fileList = options.themes
    .map(theme => {
      const files = [`\`${theme.folderName}/manifest.json\``];
      if (theme.iconPaths && theme.iconPaths.length > 0) {
        files.push(
          theme.iconPaths
            .map(path => `\`${theme.folderName}/${path}\``)
            .join(", ")
        );
      }
      return `- ${files.join(" + ")} — ${theme.displayName}`;
    })
    .join("\n");

  const themeChoices = options.themes
    .map(
      theme => `- **${theme.displayName}** — folder \`${theme.folderName}/\``
    )
    .join("\n");

  const hasIcons = options.themes.some(
    theme => (theme.iconPaths?.length ?? 0) > 0
  );
  const iconNote = hasIcons
    ? `
If a theme references icons, copy the PNG files into the theme folder using the
paths from \`manifest.json\` before installing the add-on.
`
    : "";

  return `# Installing ${displayName}

Generated by \`@razorwind/thunderbird\`.

These themes target [Mozilla Thunderbird](https://www.thunderbird.net/). Install
steps follow the same pattern as
[Dracula for Thunderbird](https://draculatheme.com/thunderbird).

## Files

${fileList}
${iconNote}
## Setup

1. Zip the contents of a generated theme folder (for example \`${primary.folderName}/\`)
   so that \`manifest.json\` is at the root of the archive.

2. Open Thunderbird and go to **Settings** (or **Preferences**) → **Add-ons and Themes**.

3. Click the gear icon and choose **Install Add-on From File…**.

4. Select the ZIP file. Thunderbird applies the theme immediately.

5. Repeat for each theme variant you want installed.

To publish publicly, upload the ZIP to
[Thunderbird Add-ons](https://addons.thunderbird.net/).

### Optional: tweak message colors

Some message text, background, and link colors are controlled separately from
the theme manifest:

1. Open Thunderbird.
2. Go to **Settings** → **General** → **Language & Appearance** → **Fonts & Colors** → **Colors…**
3. Adjust the colors to your liking.

## Select / load theme

Thunderbird applies a theme as soon as the add-on is installed. To switch themes,
open **Add-ons and Themes**, disable one theme add-on and enable another:

${themeChoices}
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: ThunderbirdTheme): string {
  return resolveThemeDisplayName(theme);
}
