
// Generated by powerlines
// Do not edit this file directly

export interface SyncGeneratorSchema {
 /**
  * Mode
  * 
  * The mode to use when running Razorwind generate
  * 
  * @default "production"
  * 
  * @enum development,production
 */
 mode?: string,

 /**
  * Target Name
  * 
  * The name of the target to use when running Razorwind generate
  * 
  * 
  * @$default generate
 */
 targetName?: string,

 /**
  * Out of Sync Message
  * 
  * The message to display when Razorwind generated files are out of sync
  * 
  * @default "Razorwind generated files are out of sync. Run `nx sync` to regenerate."
 */
 outOfSyncMessage?: string,
}

