/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { themeDisplayName as resolveThemeDisplayName } from "@razorwind/core/utils";
import type { ZshTheme } from "./types";

/**
 * Build Oh My Zsh INSTALL.md for generated `*.zsh-theme` files.
 *
 * Steps mirror the [Dracula Zsh](https://draculatheme.com/zsh) Oh My Zsh
 * activation flow: copy into the themes directory, set `ZSH_THEME`, reload.
 */
export function renderInstallMd(options: {
  themes: Array<{ name: string; displayName: string; fileName: string }>;
}): string {
  const primary = options.themes[0]!;
  const displayName =
    options.themes.length === 1 ? primary.displayName : "Oh My Zsh Themes";

  const fileList = options.themes
    .map(
      theme =>
        `- \`${theme.fileName}\` — ${theme.displayName} (\`ZSH_THEME="${theme.name}"\`)`
    )
    .join("\n");

  const themeChoices = options.themes
    .map(theme => `- \`${theme.name}\` (${theme.displayName})`)
    .join("\n");

  return `# Installing ${displayName}

Generated by \`@razorwind/zsh\`.

These themes target [Oh My Zsh](https://ohmyz.sh/). Install steps follow the
same pattern as [Dracula for Zsh](https://draculatheme.com/zsh).

## Files

${fileList}

## Setup

1. Copy each \`*.zsh-theme\` into your Oh My Zsh themes directory (prefer custom):

\`\`\`sh
mkdir -p "\${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/themes"
cp *.zsh-theme "\${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/themes/"
\`\`\`

Or into the built-in themes folder:

\`\`\`sh
cp *.zsh-theme "\${ZSH:-\$HOME/.oh-my-zsh}/themes/"
\`\`\`

2. Open \`~/.zshrc\` and set \`ZSH_THEME\` to the theme basename (no extension):

\`\`\`sh
ZSH_THEME="${primary.name}"
\`\`\`

Available ids:

${themeChoices}

3. Reload the shell:

\`\`\`sh
source ~/.zshrc
\`\`\`

## Select / load theme

\`ZSH_THEME\` must match the \`*.zsh-theme\` filename without the extension
(e.g. \`${primary.fileName}\` → \`${primary.name}\`).
`;
}

/**
 * Title-case a theme name for display when \`displayName\` is omitted.
 */
export function themeDisplayName(theme: ZshTheme): string {
  return resolveThemeDisplayName(theme);
}
