
// Generated by powerlines
// Do not edit this file directly

export interface GenerateExecutorSchema {
 /**
  * The path to the configuration file
  * 
  * @default "{projectRoot}/razorwind.config.ts"
 */
 configFile: string,

 /**
  * The mode to use
  * 
  * @default "production"
  * 
  * @enum development,production
 */
 mode: string,

 /**
  * The path to a directory containing component directories or files
  * 
 */
 componentsPath?: string,

 /**
  * The path to the tokens.json file
  * 
 */
 tokensPath?: string,
}

