
// Generated by powerlines
// Do not edit this file directly

export interface GenerateExecutorSchema {
 /**
  * The path to the configuration file
  * 
 */
 configFile: string,

 /**
  * The mode to use
  * 
  * @default "production"
  * 
  * @enum development,production
 */
 mode: string,

 /**
  * The path to a directory containing component directories or files, or an array of paths
  * 
  * 
  * @oneOf [object Object],[object Object]
 */
 componentsPath?: string | string[],

 /**
  * The path to the tokens.json file, or an array of paths
  * 
  * 
  * @oneOf [object Object],[object Object]
 */
 tokensPath?: string | string[],

 /**
  * Enable Style Dictionary verbose logging (`log.verbosity: "verbose"`)
  * 
  * @default false
 */
 verbose?: boolean,
}

