/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { GeneratorFunctionResult } from "@power-plant/core";
import { definePlugin } from "@razorwind/core/plugin";
import type { Schema } from "@razorwind/core/schema";
import { createDocument } from "@razorwind/core/utils";
import { dirname, join } from "node:path";
import { DEFAULT_SHORTHANDS } from "./eslint-runtime";
import { flattenTokens } from "./flatten";
import { collectTamaguiVocabulary, type TamaguiVocabulary } from "./generate";
import type {
  GuardrailTheme,
  GuardrailTokenCategory,
  TamaguiEslintPluginOptions
} from "./types";

export type {
  GuardrailOptions,
  GuardrailRuleId,
  GuardrailSeverity,
  GuardrailTheme,
  GuardrailTokenCategory,
  TamaguiEslintPluginOptions
} from "./types";

const DEFAULT_ESLINT_PATH = "eslint/tamagui/razorwind-guardrails.mjs";
const DEFAULT_PREFIX = "design-system";
const DEFAULT_RUNTIME_IMPORT = "@razorwind/tamagui/eslint-runtime";

/** `createTokens` shadow buckets, referenced as `<bucket>.<key>` in v3. */
const SHADOW_BUCKETS = [
  "shadow",
  "insetShadow",
  "dropShadow",
  "textShadow",
  "boxShadow"
] as const;

function sortNames(names: Iterable<string>): string[] {
  return [...new Set(names)].toSorted((a, b) =>
    a.localeCompare(b, undefined, { numeric: true })
  );
}

/**
 * Build the guardrail theme manifest from the names the generated Tamagui
 * config defines: `createTokens` keys, `createThemes` values and `createFont`
 * keys, under the category a v3 style prop resolves bare names against.
 */
export function buildGuardrailTheme(
  vocabulary: TamaguiVocabulary,
  options: {
    name?: string;
    version?: string;
    prefix?: string;
    shorthands?: Record<string, string>;
  } = {}
): GuardrailTheme {
  const { tokens, fonts } = vocabulary;
  const categories: Partial<Record<GuardrailTokenCategory, Iterable<string>>> =
    {
      color: [...(tokens.color ?? []), ...vocabulary.themeKeys],
      space: tokens.space ?? [],
      size: tokens.size ?? [],
      radius: tokens.radius ?? [],
      zIndex: tokens.zIndex ?? [],
      fontFamily: fonts.map(font => font.key),
      fontSize: fonts.flatMap(font => Object.keys(font.size)),
      fontWeight: fonts.flatMap(font => Object.keys(font.weight)),
      lineHeight: fonts.flatMap(font => Object.keys(font.lineHeight)),
      letterSpacing: fonts.flatMap(font => Object.keys(font.letterSpacing)),
      shadow: SHADOW_BUCKETS.flatMap(bucket =>
        (tokens[bucket] ?? []).map(key => `${bucket}.${key}`)
      )
    };

  const themes = [
    "light",
    ...(vocabulary.hasDark ? ["dark"] : []),
    ...vocabulary.childThemes
  ];

  return {
    name: options.name ?? DEFAULT_PREFIX,
    version: options.version ?? "0.0.0",
    prefix: options.prefix ?? DEFAULT_PREFIX,
    themes,
    tokens: Object.fromEntries(
      Object.entries(categories)
        .map(([category, names]) => [category, sortNames(names)] as const)
        .filter(([, names]) => names.length > 0)
    ),
    shorthands: { ...DEFAULT_SHORTHANDS, ...options.shorthands }
  };
}

/**
 * Render the ESLint plugin module that binds the guardrail runtime to the
 * schema-derived Tamagui vocabulary.
 */
export function renderEslintPlugin(
  theme: GuardrailTheme,
  options: Pick<TamaguiEslintPluginOptions, "runtimeImport"> = {}
): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;

  return `// Generated by @razorwind/tamagui. Do not edit by hand: re-run
// Razorwind generate when design tokens change.
//
//   import guardrails from "./<path-to-this-file>";
//   export default [
//     ...,
//     guardrails({ files: ["src/**/*.{ts,tsx}"] })
//   ];

import { createGuardrails } from ${JSON.stringify(runtimeImport)};

export const theme = ${JSON.stringify(theme, null, 2)};

const guardrails = createGuardrails(theme);

export const plugin = guardrails.plugin;
export const rules = guardrails.rules;
export const defaultSeverity = guardrails.defaultSeverity;

export default guardrails.config;
`;
}

/**
 * Build ESLint guardrails INSTALL.md for the generated plugin module.
 */
export function renderEslintInstallMd(options: {
  eslintPath: string;
  theme: GuardrailTheme;
}): string {
  const { eslintPath, theme } = options;
  const categories = Object.entries(theme.tokens)
    .map(([category, names]) => `- \`${category}\` (${names.length})`)
    .join("\n");

  return `# Installing Tamagui ESLint Design-System Guardrails

Generated by \`@razorwind/tamagui\` for Tamagui v3 flat values.

## Files

- \`${eslintPath}\` — ESLint flat-config plugin whose rules are derived from the design tokens

## Setup

1. Install the runtime the generated module imports:

\`\`\`bash
pnpm add -D @razorwind/tamagui
\`\`\`

2. Add the guardrails to \`eslint.config.mjs\`, next to Tamagui's own
   \`valid-flat-values\` rule (grammar and typos):

\`\`\`js
import guardrails from "./${eslintPath}";

export default [
  // ...
  guardrails({
    files: ["src/**/*.{ts,tsx}"],
    severity: { "no-stock-palette": "error" }
  })
];
\`\`\`

3. Deliberate one-offs carry an inline, reviewable exception:

\`\`\`tsx
// eslint-disable-next-line ${theme.prefix}/no-color-literal -- <reason>
\`\`\`

## Token categories

Rules for a category are only enabled when the generated config defines it:

${categories || "- _(none)_"}

## Regenerate

Re-run Razorwind generate when design tokens change so \`${eslintPath}\` stays in sync.
`;
}

/**
 * Generate an ESLint guardrails plugin aligned with the generated Tamagui v3
 * config. Returns no files unless `target` is `"v3"`.
 */
export async function generateEslintGuardrails(
  spec: Schema,
  options: TamaguiEslintPluginOptions = {}
): Promise<GeneratorFunctionResult<Schema, TamaguiEslintPluginOptions>> {
  if (options.target !== "v3") {
    return {};
  }

  const hasTokens = spec.tokens && Object.keys(spec.tokens).length > 0;
  const hasFonts = spec.fonts && Object.keys(spec.fonts).length > 0;
  if (!hasTokens && !hasFonts) {
    return {};
  }

  const flat = hasTokens ? flattenTokens(spec.tokens, options) : [];
  const theme = buildGuardrailTheme(collectTamaguiVocabulary(spec, flat), {
    name: spec.name,
    prefix: options.prefix,
    shorthands: options.shorthands
  });
  if (Object.keys(theme.tokens).length === 0) {
    return {};
  }

  const eslintPath = options.eslintPath ?? DEFAULT_ESLINT_PATH;
  const installPath = join(dirname(eslintPath), "INSTALL.md");
  const meta = { name: "razorwind-tamagui-eslint" };

  return {
    [eslintPath]: createDocument<Schema, TamaguiEslintPluginOptions>(
      eslintPath,
      renderEslintPlugin(theme, options),
      meta,
      undefined,
      "javascript"
    ),
    [installPath]: createDocument<Schema, TamaguiEslintPluginOptions>(
      installPath,
      options.installGuide ?? renderEslintInstallMd({ eslintPath, theme }),
      meta,
      undefined,
      "markdown"
    )
  };
}

/**
 * Razorwind plugin: generate an ESLint guardrails plugin that keeps Tamagui v3
 * flat style values aligned with the schema's design tokens. Only emits when
 * `target` is `"v3"`.
 *
 * @example
 * ```ts
 * import { defineConfig } from "@razorwind/core";
 * import tamagui from "@razorwind/tamagui";
 * import tamaguiEslint from "@razorwind/tamagui/eslint";
 *
 * export default defineConfig({
 *   plugins: [tamagui({ target: "v3" }), tamaguiEslint({ target: "v3" })]
 * });
 * ```
 */
export default definePlugin((options?: TamaguiEslintPluginOptions) => ({
  name: "tamagui:eslint",
  generate: async spec => generateEslintGuardrails(spec, options ?? {})
}));
