/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Build Tamagui INSTALL.md for generated config file.
 *
 * @see https://tamagui.dev/docs/core/config-v5
 */
export function renderInstallMd(options: { outputPath: string }): string {
  return `# Installing Tamagui Config

Generated by \`@razorwind/tamagui\`.

## Files

- \`${options.outputPath}\` — Tamagui v5 config (\`createTamagui\` + \`createV5Theme\` with light and dark)

## Setup

1. Point Tamagui at the generated config:

\`\`\`ts
import config from "./${options.outputPath}";

export default config;
\`\`\`

2. Wrap your app with Tamagui. The generated file includes both \`light\` and \`dark\` themes:

\`\`\`tsx
import { TamaguiProvider } from "tamagui";
import config from "./${options.outputPath}";

export function App() {
  return (
    <TamaguiProvider config={config} defaultTheme="light">
      {/* … */}
    </TamaguiProvider>
  );
}
\`\`\`

3. Use generated tokens with Tamagui style props
   ([styles](https://tamagui.dev/docs/intro/styles), [tokens](https://tamagui.dev/docs/core/tokens)):

- \`color="$primary"\` / \`padding="$sm"\` / \`borderRadius="$md"\`
- \`fontFamily="$body"\` / \`fontSize="$true"\` / \`fontWeight="$bold"\`
- Language variants: \`<FontLanguage body="cn">\` when a \`body_cn\` font is generated
- \`boxShadow="$shadow.sm"\` / \`boxShadow="$insetShadow.xs"\`
- \`textShadow="$textShadow.sm"\`
- \`filter="$dropShadow.sm"\`

## Regenerate

Re-run Razorwind generate when tokens change so \`${options.outputPath}\` stays aligned with your design system.
`;
}
