/* -------------------------------------------------------------------

                    🗲 Storm Software - Razorwind

 This code was released as part of the Razorwind project. Razorwind
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/razorwind.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/razorwind
 Documentation:            https://docs.stormsoftware.com/projects/razorwind
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * VS Code extension INSTALL.md for generated theme packages.
 *
 * @see https://code.visualstudio.com/api/extension-guides/color-theme
 */
export function renderInstallMd(options: {
  displayName: string;
  extensionName: string;
  themes: Array<{ label: string; path: string }>;
  includeScripts: boolean;
}): string {
  const themeFiles = options.themes
    .map(theme => `- \`${theme.path}\` — ${theme.label}`)
    .join("\n");
  const themeLabels = options.themes
    .map(theme => `- **${theme.label}**`)
    .join("\n");
  const vsixPath = `./dist/${options.extensionName}.vsix`;

  const packageSection = options.includeScripts
    ? `
## Package VSIX

From the generated extension directory:

\`\`\`bash
pnpm package-vsix
\`\`\`

This writes \`${vsixPath}\`.

## Install from VSIX

1. Open the Extensions view (\`Ctrl+Shift+X\` / \`Cmd+Shift+X\`)
2. Open the **⋯** menu → **Install from VSIX...**
3. Select \`${vsixPath}\`
`
    : `
## Install locally

Open this folder in VS Code / Cursor and press **F5** to launch an Extension Development Host, or copy \`themes/*.json\` into a local extension package.
`;

  return `# Installing ${options.displayName}

Generated by \`@razorwind/vsce\`.

## Files

- \`package.json\` — extension manifest (\`contributes.themes\`)
- \`themes/*.json\` — color theme documents
${themeFiles}
${packageSection}
## Select theme

Open the Command Palette (\`Ctrl+Shift+P\` / \`Cmd+Shift+P\`) → **Preferences: Color Theme** → choose:

${themeLabels}
`;
}
